spring:
  application:
    name: core-service
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Ensure this matches your Eureka server URL
    register-with-eureka: true
    fetch-registry: true